name: CI

on:
  push:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        elixir:
          - "1.13"
          - "1.14"
          - "1.15"
        otp:
          - "24"
          - "25"
          - "26"
        include:
          - elixir: "1.15"
            otp: "26"
            format: true
        exclude:
          - elixir: "1.13"
            otp: "26"
          - elixir: "1.14"
            otp: "26"

    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
      with:
        use-policy-store: true
        api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

    - uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Restore deps cache
      uses: step-security/runs-on-cache@c5b0cba15d05488ebc630ad8d1e95b3d9b35ac73 # v5.0.7
      with:
        path: |
          deps
          _build
        key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}-git-${{ github.sha }}
        restore-keys: |
          deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Install package dependencies
      run: mix deps.get

    - name: Check code format
      run: mix format --check-formatted
      if: ${{ matrix.format }}

    - name: Compile dependencies
      run: mix compile
      env:
        MIX_ENV: test

    - name: Run unit tests
      run: mix test

    - name: Cache/uncache PLTs
      uses: step-security/runs-on-cache@c5b0cba15d05488ebc630ad8d1e95b3d9b35ac73 # v5.0.7
      with:
        path: |
          priv/plts
        key: "${{ runner.os }}-\
              erlang-${{ matrix.otp }}-\
              elixir-${{ matrix.elixir }}-\
              ${{ hashFiles('mix.lock') }}"

    - name: Run Dialyzer
      run: mix dialyzer
