name: CI

on:
  push:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        elixir:
          - "1.13"
          - "1.14"
          - "1.15"
        otp:
          - "24"
          - "25"
          - "26"
        include:
          - elixir: "1.15"
            otp: "26"
            format: true
        exclude:
          - elixir: "1.13"
            otp: "26"
          - elixir: "1.14"
            otp: "26"

    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2
      with:
        use-policy-store: true
        api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v2

    - uses: step-security/setup-beam@05e480cfdc64c72ab6c25b134dd1f57e29776c84 # v1.24.1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Restore deps cache
      uses: step-security/runs-on-cache@e61ed9b0206c630e9a6bb5f12ca4cd78ae7bbe93 # v5.0.7
      with:
        path: |
          deps
          _build
        key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}-git-${{ github.sha }}
        restore-keys: |
          deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Install package dependencies
      run: mix deps.get

    - name: Check code format
      run: mix format --check-formatted
      if: ${{ matrix.format }}

    - name: Compile dependencies
      run: mix compile
      env:
        MIX_ENV: test

    - name: Run unit tests
      run: mix test

    - name: Cache/uncache PLTs
      uses: step-security/runs-on-cache@e61ed9b0206c630e9a6bb5f12ca4cd78ae7bbe93 # v5.0.7
      with:
        path: |
          priv/plts
        key: "${{ runner.os }}-\
              erlang-${{ matrix.otp }}-\
              elixir-${{ matrix.elixir }}-\
              ${{ hashFiles('mix.lock') }}"

    - name: Run Dialyzer
      run: mix dialyzer
